DISCLAIMER = "This is general legal information, not legal advice. Consult a licensed advocate for your specific situation."
OUT_OF_SCOPE_MESSAGE = "I can only help with Indian legal information and first-responder legal situations. Please ask a legal question."
RESPONSE_SCOPE_FALLBACK = "I wasn't able to generate a response within scope for that question. Please rephrase or ask a specific legal question."
RATE_LIMIT_MESSAGE = "The assistant is temporarily busy, please try again in a moment"
SESSION_LIMIT_MESSAGE = "This session has reached its request limit. Please try again later."
CITATION_UNCERTAINTY_MESSAGE = "I cannot confidently verify the exact statute or section number for that situation. Please consult the current official text of the law or a licensed advocate."
INSUFFICIENT_EVIDENCE_MESSAGE = "I don't have sufficient authoritative material in the available legal sources to answer this reliably. Please consult a licensed advocate or the relevant official authority."
EMERGENCY_MESSAGE = "Your immediate safety appears to be the priority. If there is immediate danger, contact the appropriate local emergency, police, or medical service now and move to a safer place if you can. I cannot assess the danger from here."
